import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const generateResumePDF = async () => {
  // Get the results container
  const resultsElement = document.getElementById('results-container');
  
  if (!resultsElement) {
    throw new Error('Results not found');
  }

  // Show loading overlay
  const loadingOverlay = document.createElement('div');
  loadingOverlay.id = 'pdf-loading';
  loadingOverlay.className = 'fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50';
  loadingOverlay.innerHTML = `
    <div class="bg-white rounded-lg p-6 shadow-xl">
      <div class="flex items-center gap-3">
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
        <span class="text-lg font-semibold">Generating PDF...</span>
      </div>
    </div>
  `;
  document.body.appendChild(loadingOverlay);

  try {
    // Temporarily hide copy buttons for cleaner PDF
    const copyButtons = resultsElement.querySelectorAll('.pdf-hide-button');
    copyButtons.forEach(btn => btn.style.visibility = 'hidden');

    // Generate canvas from HTML
    const canvas = await html2canvas(resultsElement, {
      scale: 2, // Higher quality
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
      windowWidth: resultsElement.scrollWidth,
      windowHeight: resultsElement.scrollHeight
    });

    // Show copy buttons again
    copyButtons.forEach(btn => btn.style.visibility = 'visible');

    // Calculate dimensions
    const imgWidth = 210; // A4 width in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    const pageHeight = 297; // A4 height in mm
    
    const imgData = canvas.toDataURL('image/png');
    
    // Create PDF with compression
    const pdf = new jsPDF({
      orientation: 'p',
      unit: 'mm',
      format: 'a4',
      compress: true
    });

    // Add metadata
    pdf.setProperties({
      title: 'Resume Optimization Recommendations',
      subject: 'Resume Analysis by ResuMend',
      author: 'ResuMend',
      keywords: 'resume, optimization, recommendations',
      creator: 'ResuMend App'
    });
    
    let heightLeft = imgHeight;
    let position = 0;

    // Add first page
    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    // Add additional pages if content is longer than one page
    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    // Add footer to all pages
    const pageCount = pdf.internal.getNumberOfPages();
    pdf.setFontSize(10);
    pdf.setTextColor(150);
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i);
      pdf.text('Generated by ResuMend', 105, 290, { align: 'center' });
      pdf.text(`Page ${i} of ${pageCount}`, 200, 290, { align: 'right' });
    }

    // Generate filename with timestamp
    const timestamp = new Date().toISOString().split('T')[0];
    const filename = `resumend-recommendations-${timestamp}.pdf`;
    
    // Save the PDF
    pdf.save(filename);

    return { success: true, filename };

  } catch (error) {
    console.error('PDF generation error:', error);
    throw error;
  } finally {
    // Remove loading overlay
    const overlay = document.getElementById('pdf-loading');
    if (overlay) {
      overlay.remove();
    }
  }
};